### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by jacksongoode** [pulse-browser/experiment#15]
Not sure if it's that point in development, but ready-built packages would be nice for folks to test out.

**Comment by trickypr** [comment]
You can [grab an build artifact](https://github.com/pulse-browser/experiment#testing-build-artifacts) (for Linux) from any commit on this repo if you want to test it. 

I don't want people using it as their primary browser or filing issues against it just yet, so I am not making easily accessible releases.

**Comment by jacksongoode** [comment]
Would there be a path to build it for macOS?

**Comment by ioc2e3** [comment]
> 如果您想測試它，您可以從此儲存庫上的任何提交中[取得建置工件（適用於 Linux）。](https://github.com/pulse-browser/experiment#testing-build-artifacts)
> 
> 我不希望人們使用它作為主要瀏覽器或針對它提出問題，因此我不會發布易於訪問的版本。

about experiment ...

Will there be a Windows version?

Will there be a Portable version?

Will there be a Traditional Chinese interface?

.

**Comment by trickypr** [comment]
> Would there be a path to build it for macOS?

I haven't setup macos builds for the [runtime](https://github.com/pulse-browser/experiment-runtime).

> Will there be a Windows [or macOS] version?

Not soon. MacOS probably eventually. Windows only if I get a release before windows 10 EoL. Windows will probibly be supported until Windows 10 EoL, because I don't want to buy hardware for an OS I don't use

> Portable version

The Linux version is technically portable. Will cross that bridge for macOS and Windows when I get to it.

> Traditional Chinese interface

If a set of contributors want to provide a translation once I have a stable release, sure. At the moment, this is just a prototype with none of the infra for translation
